// <auto-generated />
using System;
using DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DbContextDemo))]
    [Migration("20251119095316_Car_CarOption_relation")]
    partial class Car_CarOption_relation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_CarOption", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("Car_CarOption");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            OptionId = 1
                        },
                        new
                        {
                            CarId = 1,
                            OptionId = 2
                        },
                        new
                        {
                            CarId = 1,
                            OptionId = 3
                        },
                        new
                        {
                            CarId = 2,
                            OptionId = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Brand");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UK_Brand_name");

                    b.ToTable("Brand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 2,
                            Name = "VW"
                        });
                });

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Car");

                    b.HasIndex("BrandId");

                    b.ToTable("Vrooooom", null, t =>
                        {
                            t.HasCheckConstraint("CK_Car__Price", "[Price] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Model = "MX-5",
                            Price = 1000m,
                            RegistrationDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "FOR_PARTS"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Model = "Polo",
                            Price = 100m,
                            RegistrationDate = new DateTime(2025, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = "FOR_PARTS"
                        });
                });

            modelBuilder.Entity("Domain.Models.CarOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_CarOption");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarOption", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clignotant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Siège chauffant"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ouverture de proximité"
                        });
                });

            modelBuilder.Entity("Car_CarOption", b =>
                {
                    b.HasOne("Domain.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.CarOption", null)
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Car", b =>
                {
                    b.HasOne("Domain.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Domain.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
